# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captcha',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='captcha',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='captcha',
            name='name',
            field=models.TextField(),
        ),
    ]
