# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-05 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170805_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='captcha',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
