# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170805_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captcha',
            name='name',
        ),
        migrations.AddField(
            model_name='captcha',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='captcha',
            name='first',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='captcha',
            name='last',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
